FROM microsoft/dotnet:sdk
WORKDIR /e-client
EXPOSE 80

COPY ./API/E-Client .

COPY ././Domain-Core /Domain-Core

RUN dotnet restore
RUN dotnet publish -c Release -o out

ENTRYPOINT ["dotnet", "out/e-client.dll"]
